version: '3'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
#      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - microservices-net

  gateway:
    image : adityamaskar1/vp-gateway
    container_name: gateway
    depends_on:
      - service-discovery
    ports:
      - "1234:1234"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
    networks:
      - microservices-net

  service-discovery:
    image: adityamaskar1/vp-discovery-server
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  visitor-app:
    image: adityamaskar1/visitor-management-project
    container_name: visitor-app
    depends_on:
      - service-discovery
      - gateway
    environment:
      - notification-service-endpoint=http://notification-service/notify/tracking
      - spring.datasource.url=jdbc:mysql://mysql:3306/visitorappdb2
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - spring.datasource.password=mysql
      - spring.kafka.bootstrap-servers=http://broker:9092
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    networks:
      - microservices-net

  notification-service:
    image: adityamaskar1/vp-notification-service
    container_name: notification-service
    depends_on:
      - service-discovery
      - gateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka/
      - spring.kafka.bootstrap-servers=http://broker:9092
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge





