#we don't need gateway incase of the kubernetes.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: adityamaskar1/vp-gateway
          ports:
            - containerPort: 1234
          env:
#            - name: eureka.client.serviceUrl.defaultZone
#              value: http://service-discovery-service:8761/eureka/
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: vp-configs
                  key: discovery-service-url
            - name: visitor-service-name
              value: vp-app-service
            - name: visitor-service-name-uri
              value: http://vp-app-service:8000

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 1234
      targetPort: 1234
      nodePort: 31002
