apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: adityamaskar1/vp-notification-service
          ports:
            - containerPort: 1235
          env:
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: eureka-configmap
                  key: discovery-service-url
            - name: spring.kafka.bootstrap-servers
              value: http://broker-service:9092

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-service
spec:
#  type: LoadBalancer
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 1235
      targetPort: 1235
#      nodePort: 31002
