apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-app
          image: adityamaskar1/vp-notification-service
          ports:
            - containerPort: 1235
          env:
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: vp-configs
                  key: discovery-service-url
            - name: spring.kafka.bootstrap-servers
              valueFrom:
                configMapKeyRef:
                  name: vp-configs
                  key: kafka-broker
            - name: spring.zipkin.base-url
              valueFrom:
                configMapKeyRef:
                  name: vp-configs
                  key: zipkin-url
---
apiVersion: v1
kind: Service
metadata:
  name: notification-app-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 1235
      targetPort: 1235
