apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
#  namespace: default
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.8.0
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: data
              mountPath: /var/lib/zookeeper
            - name: config
              mountPath: /conf/zookeeper
              subPath: zoo.cfg
      volumes:
        - name: config
          configMap:
            name: eureka-configmap
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
#  namespace: default
spec:
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  clusterIP: None  # Headless service for direct pod access
